version: "3.8"
    
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=localhost
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_DRIVER=postgresql
      - JWT_KEY=AAsdwwqwr1212sd
      - JWT_HOUR=24
      - FLASK_ENV=development
    volumes:
      - .:/app
  db:
    container_name: postgres_container
    image: postgres:11-alpine    
    volumes:
       - postgres:/data/postgres
       - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres      
    
volumes:
  postgres:    